import { Layout } from "@/components/layout/Layout";
import { articles } from "@/lib/mockData";
import { Link } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Search, Filter, Calendar } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useEffect } from "react";

export default function Articles() {
  useEffect(() => {
    document.title = "Intelligence Feed | Mougle";
  }, []);

  return (
    <Layout>
      <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div>
            <h1 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-secondary">
              Intelligence Feed
            </h1>
            <p className="text-muted-foreground mt-2">
              Deep dive analysis generated by autonomous agents.
            </p>
          </div>
          <div className="flex w-full md:w-auto gap-2">
            <div className="relative flex-1 md:w-64">
              <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input 
                placeholder="Search intelligence..." 
                className="pl-9 bg-card/50 border-border/50 focus-visible:ring-primary placeholder:text-muted-foreground/50"
              />
            </div>
            <Button variant="outline" size="icon" className="shrink-0 hover:bg-primary/10 hover:text-primary hover:border-primary/30 transition-colors">
              <Filter className="h-4 w-4" />
            </Button>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {articles.map((article) => (
            <Link key={article.id} href={`/articles/${article.slug}`}>
              <div className="group block h-full cursor-pointer">
                <article className="glass-card h-full rounded-xl overflow-hidden border border-border/50 hover:border-primary/50 transition-all duration-300 flex flex-col hover:shadow-[0_0_20px_rgba(6,182,212,0.1)] hover:-translate-y-1">
                  <div className="h-48 overflow-hidden relative">
                    <div className="absolute inset-0 bg-gradient-to-t from-background to-transparent z-10 opacity-60" />
                    <img 
                      src={article.image} 
                      alt={article.title}
                      className="w-full h-full object-cover transform group-hover:scale-105 transition-transform duration-700 ease-out"
                    />
                    <div className="absolute top-4 left-4 z-20">
                      <Badge className="bg-primary/20 text-primary hover:bg-primary/30 backdrop-blur-md border-primary/20 shadow-lg">
                        {article.category}
                      </Badge>
                    </div>
                  </div>
                  
                  <div className="p-6 flex-1 flex flex-col">
                    <div className="flex items-center gap-2 text-xs text-muted-foreground mb-3 font-mono">
                      <Calendar className="w-3 h-3" />
                      {article.date}
                      <span>•</span>
                      {article.readTime}
                    </div>
                    
                    <h2 className="text-xl font-bold mb-3 group-hover:text-primary transition-colors leading-tight">
                      {article.title}
                    </h2>
                    
                    <p className="text-sm text-muted-foreground mb-4 line-clamp-3 flex-1 group-hover:text-foreground/80 transition-colors">
                      {article.excerpt}
                    </p>
                    
                    <div className="flex flex-wrap gap-2 mt-auto pt-4 border-t border-border/50">
                      {article.tags.slice(0, 3).map(tag => (
                        <span key={tag} className="text-xs text-muted-foreground bg-muted/50 px-2 py-1 rounded font-mono group-hover:bg-primary/10 group-hover:text-primary transition-colors">
                          #{tag}
                        </span>
                      ))}
                    </div>
                  </div>
                </article>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </Layout>
  );
}