import type { LocaleLexicon } from "./types";

// German (de) — DE/AT/CH variants. Includes umlaut + ae/oe/ue forms because
// `normalizeAudienceText` does not transliterate them.
export const DE_LEXICON: LocaleLexicon = {
  abuse: [
    "idiot", "idiotin", "dumm", "dummkopf", "dummerchen", "halt die klappe",
    "halt den mund", "halt die schnauze", "halt die fresse", "klappe halten",
    "arschloch", "arschloecher", "arschlöcher", "blöd", "blod", "bloed",
    "blöder", "bloeder", "blödmann", "blodmann", "bloedmann", "trottel",
    "trottelin", "depp", "deppin", "vollpfosten", "pfosten", "wichser",
    "wixer", "spast", "spasti", "behindert", "behinderte", "behinderter",
    "schwachkopf", "schwachsinnig", "schwachmat", "vollhorst", "horst",
    "honk", "lutscher", "luetscher", "lümmel", "luemmel", "looser",
    "loser", "versager", "versagerin", "drecksau", "schweinehund",
    "schwein", "sau", "miststück", "miststueck", "ratte", "fotze",
    "schlampe", "hure", "huren", "missgeburt", "krüppel", "krueppel",
    "kruppel", "halts maul", "halt s maul", "halts maul du",
    "verpiss dich", "hau ab", "verschwinde", "geh sterben", "stirb",
    "stirb doch", "krepier", "krepiere", "fick dich", "fick deine mutter",
    "leck mich", "leck mich am arsch", "leck mir am arsch",
  ],
  hate: [
    "ich hasse alle", "tod den", "tod allen", "raus mit den", "raus mit denen",
    "raus mit allen", "raus aus meinem land", "auslander raus",
    "ausländer raus", "auslaender raus", "kanaken raus", "juden raus",
    "moslems raus", "muslime raus", "fluechtlinge raus", "flüchtlinge raus",
    "fluechtlinge weg", "alle juden sollten", "alle muslime sollten",
    "alle moslems sollten", "alle schwarzen sollten", "alle zigeuner sollten",
    "alle chinesen sollten", "alle asiaten sollten", "alle araber sollten",
    "alle tuerken sollten", "alle türken sollten", "alle homos sollten",
    "alle schwuchteln", "schwuchtel", "schwuchteln", "drecksjuden",
    "drecksjude", "dreckstuerken", "dreckstürken", "dreckskanaken",
    "drecksaraber", "drecksneger", "neger", "negerin", "untermenschen",
    "untermensch", "minderwertige rasse", "minderwertige rassen",
    "ueberlegene rasse", "überlegene rasse", "ethnische saeuberung",
    "ethnische säuberung", "endloesung", "endlösung", "gaskammer",
    "ab nach auschwitz", "vergasen", "vergast", "haengt sie", "hängt sie",
    "verbrennt sie", "lyncht sie", "knueppelt sie", "knüppelt sie",
    "schlagt sie tot", "totet alle", "tötet alle", "ausrotten", "ausrottet",
    "ungeziefer", "ratten", "kakerlaken", "parasiten", "pack",
    "sollten alle sterben",
  ],
  spam: [
    "gratis geld", "hier klicken", "klick hier", "abonniere meinen kanal",
    "abonniert meinen kanal", "abonnier meinen kanal", "schau auf mein profil",
    "schau in meine bio", "link in der bio", "link in bio",
    "verdiene geld schnell", "schnell geld verdienen", "geld verdienen von zuhause",
    "von zuhause arbeiten", "passives einkommen", "nebenverdienst",
    "limitiertes angebot", "exklusives angebot", "exklusive aktion",
    "jetzt kaufen", "kostenloser versand", "gratis versand", "rabatt von",
    "kostenloses geschenk", "gratis geschenk", "du hast gewonnen",
    "sie haben gewonnen", "glueckwunsch du hast gewonnen",
    "glückwunsch du hast gewonnen", "hol dir deinen preis",
    "fordere deinen preis", "klick auf meinen link", "besuch meine seite",
    "besuche meine seite", "besuch meinen shop", "besuche meinen shop",
    "schau meine videos", "lass ein like da", "like und abonniere",
    "folge mir auf instagram", "folg mir auf instagram",
    "folge mir auf tiktok", "folg mir auf tiktok", "folge mir auf telegram",
    "schreib mir bei whatsapp", "schreib mir auf whatsapp", "schreib mir privat",
    "schick mir eine dm", "schreib mir eine pn", "kryptowahrung gratis",
    "kryptowährung gratis", "krypto gratis", "bitcoin gratis",
    "sichere investition", "verdopple dein geld", "garantierter gewinn",
    "garantierte gewinne", "100% gratis", "100% kostenlos",
    "voellig kostenlos", "völlig kostenlos", "kein betrug", "kein scam",
    "das ist kein spam", "geheime methode", "geheim trick", "geheimer trick",
    "kostenloser premium account", "netflix gratis", "robux gratis",
    "vbucks gratis",
  ],
};
