import type { LocaleLexicon } from "./types";

// Portuguese (pt) — covers Brazilian + European Portuguese variants.
export const PT_LEXICON: LocaleLexicon = {
  abuse: [
    "idiota", "estupido", "estúpido", "estupida", "estúpida", "imbecil",
    "imbécil", "cala boca", "cala a boca", "cale a boca", "burro", "burra",
    "otario", "otário", "otaria", "otária", "babaca", "panaca", "trouxa",
    "trouxas", "retardado", "retardada", "mongol", "mongoloide", "anormal",
    "lerdo", "lerda", "tonto", "tonta", "tapado", "tapada", "abestalhado",
    "abestalhada", "patetico", "patético", "patetica", "patética",
    "ridiculo", "ridículo", "ridicula", "ridícula", "vergonha alheia",
    "nojento", "nojenta", "asqueroso", "asquerosa", "lixo", "escoria",
    "escória", "verme", "rato", "ratazana", "perdedor", "perdedora",
    "fracassado", "fracassada", "inutil", "inútil", "morre", "vai morrer",
    "se mata", "se foda", "vai se foder", "filho da puta", "filha da puta",
    "fdp", "fdps", "corno", "corna", "cornudo", "cornuda", "viado", "viada",
    "bicha", "bichona", "frouxo", "frouxa", "covarde", "puxa saco",
    "puxa-saco", "lambe botas", "lambe-botas", "vai pro inferno",
    "vai pra puta que pariu", "vai a merda", "vai à merda", "cale-se",
    "fecha a matraca", "fecha o bico",
  ],
  hate: [
    "odeio todos os", "odeio todas as", "morte aos", "morte às", "fora os",
    "fora as", "fora do meu pais", "fora do meu país", "expulsem os",
    "expulsem as", "que morram todos os", "que morram todas as",
    "deviam morrer todos os", "deviam morrer todas as",
    "todos os imigrantes", "todos os refugiados", "todas as feministas",
    "os judeus deveriam", "os muçulmanos deveriam", "os negros deveriam",
    "os ciganos deveriam", "os chineses deveriam", "os gays deveriam",
    "os viados deveriam", "raça inferior", "raca inferior", "raça superior",
    "raca superior", "limpeza etnica", "limpeza étnica", "macaco preto",
    "macaca preta", "preto fedido", "preta fedida", "macumbeiro",
    "macumbeira", "judeu sovina", "judia sovina", "muçulmanos terroristas",
    "todo muçulmano", "todo muculmano", "todo nordestino", "todo nordestina",
    "todo paraiba", "todo paraíba", "todo baiano", "viado nojento",
    "viada nojenta", "bicha nojenta", "sapatao nojenta", "sapatão nojenta",
    "linchem os", "queimem os", "matem todos os", "matem todas as",
    "nao merecem viver", "não merecem viver", "nao sao humanos",
    "não são humanos", "sao uma praga", "são uma praga", "sao ratos",
    "são ratos", "sao animais", "são animais",
  ],
  spam: [
    "dinheiro gratis", "dinheiro grátis", "clique aqui",
    "inscreva-se no meu canal", "inscreva se no meu canal",
    "se inscreva no meu canal", "visite meu perfil", "olha meu perfil",
    "olha minha bio", "ganhe dinheiro rapido", "ganhe dinheiro rápido",
    "trabalhe em casa", "trabalho de casa", "renda extra", "renda passiva",
    "oferta limitada", "promocao exclusiva", "promoção exclusiva",
    "compre agora", "frete gratis", "frete grátis", "desconto de",
    "brinde gratis", "brinde grátis", "premio gratis", "prêmio grátis",
    "voce ganhou", "você ganhou", "parabens voce ganhou",
    "parabéns você ganhou", "resgate seu premio", "resgate seu prêmio",
    "entre no meu link", "entra no meu link", "acesse meu site",
    "visite meu site", "visita minha loja", "visite minha loja",
    "olha meus videos", "olha meus vídeos", "deixa o like e se inscreve",
    "curte e se inscreve", "me segue no instagram", "me segue no tiktok",
    "me segue no telegram", "me chama no whats", "me chama no zap",
    "manda dm", "manda direct", "envio info no direct",
    "criptomoedas gratis", "criptomoedas grátis", "bitcoin gratis",
    "bitcoin grátis", "investimento seguro", "dobre seu dinheiro",
    "lucro garantido", "ganhos garantidos", "100% gratis", "100% grátis",
    "totalmente gratis", "totalmente grátis", "nao e golpe", "não é golpe",
    "isso nao e spam", "isso não é spam", "metodo secreto", "método secreto",
    "truque secreto", "hack secreto", "conta premium gratis",
    "netflix gratis", "netflix grátis", "robux gratis", "vbucks gratis",
    "pix gratis", "pix grátis", "ganhe pix", "ganhe no pix",
  ],
};
